config/routes.rb
Rails.application.routes.draw do
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'static_pages#home'

  get 'coe' => 'static_pages#code_of_ethics'

  get 'events' => 'static_pages#events'

  resources :static_pages do
    member { post :mercury_update }
  end
  
  resources :users

  resources :announcements do
    member { post :mercury_update }
  end

  resources :forms
  
  resources :results do
    member { post :mercury_update }
    member { patch :upload_results_file }
    member { delete :delete_results_file }
  end

  mount Mercury::Engine => '/'

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :logged_in_user, only: ['edit', 'new', 'create', 'update', 'destroy']

  def edit
    @form = Form.find(params[:id])
  end
  
  def new
    @form = Form.new
  end

  def create
    # Leaving the upload form blank results in the ActionController::ParameterMissing error
    begin
      @form = Form.new(form_params)
    rescue ActionController::ParameterMissing => e
      flash[:danger] = "No file chosen."
      redirect_to(:action => :new) and return
    end
    if @form.save
      flash[:success] = "Document uploaded."
      redirect_to forms_path
    else
      redirect_to "new"
    end
  end

  def update
    # Leaving the upload form blank results in the ActionController::ParameterMissing error
    if form_params.blank?
      flash[:danger] = "No file chosen."
      redirect_to(:action => :new) and return
    end

    @form = Form.find(params[:id])

    if @form.update_attributes(form_params)
      flash[:success] = "Document uploaded."
      redirect_to forms_path
    else
      redirect_to "edit"
    end
  end

  def index
    @forms = Form.all
  end

  def show
    @form = Form.find(params[:id])
  end

  def destroy
    @form = Form.find(params[:id])
    if @form.destroy
      flash[:success] = "Document deleted."
      redirect_to forms_path
    else
      flash[:danger] = "Unable to delete document."
      redirect_to @form
    end
  end

  private

    def form_params
      params.require(:form).permit(:document)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
  def download_link(form, opts = {})
    raw "<a href=\"#{form.document.url}\" class=\"#{opts[:class]}\" download>#{form.document_file_name}</a>"
  end
end

app/views/forms/_form.html.erb
<%= download_link form %>
<% if logged_in? %>
  <p>
    <small><%=link_to "Delete", form, method: :delete, data: {confirm: "Are you sure?"} %></small>
     - <small><%=link_to "Edit", edit_form_path(form) %></small>
  </p>
<% end %>

app/views/forms/edit.html.erb
<% provide(:title, "Replace existing file") %>
<%= form_for @form, :url => @form, :html => { :multipart => true } do |f| %>
  <%= render 'shared/errors', :model => @form %>

  <%= f.label :document %>
  <p><strong>Only PDFs and Excel spreadsheets permitted.</strong></p>
  <%= f.file_field :document, class: "form-control" %>

  <%= f.submit "Upload", class: "btn btn-primary" %>
<% end %>

app/views/forms/index.html.erb
<% provide :title, "Forms" %>
<% @forms.each do |form| %>
<ul class="list-group">
  <li class="list-group-item"><%= render 'forms/form', :form => form %></li>
</ul>
<% end %>

app/views/forms/new.html.erb
<% provide(:title, "Upload new file") %>
<%= form_for @form, :url => forms_path, :html => { :multipart => true } do |f| %>
  <%= render 'shared/errors', :model => @form %>

  <%= f.label :document %>
  <p><strong>Only PDFs and Excel spreadsheets permitted.</strong></p>
  <%= f.file_field :document, class: "form-control" %>

  <%= f.submit "Upload", class: "btn btn-primary" %>
<% end %>

app/views/forms/show.html.erb
<% provide( :title, @form.document_file_name )%>
<%= render 'shared/errors', :model => @form %>
<%= render 'forms/form', :form => @form %>