config/routes.rb
Rails.application.routes.draw do
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'static_pages#home'

  get 'coe' => 'static_pages#code_of_ethics'

  get 'events' => 'static_pages#events'

  resources :static_pages do
    member { post :mercury_update }
  end
  
  resources :users

  resources :announcements do
    member { post :mercury_update }
  end

  resources :forms
  
  resources :results do
    member { post :mercury_update }
    member { patch :upload_results_file }
    member { delete :delete_results_file }
  end

  mount Mercury::Engine => '/'

end

app/views/layouts/_footer.html.erb
<div class="container" id="footer-container">
  <footer class="site-footer">
    <p class="text-right">
      <small>
        <%= link_to "Log in", login_path unless logged_in? %>
        <% if logged_in? %>
          <%= link_to "Create new user", new_user_path %>
           - <%= link_to "View users", users_path %>
           - <%= link_to "Edit account", edit_user_path(current_user) %>
           - <%= link_to "Publish announcement", new_announcement_path %>
           - <%= link_to "Upload form", new_form_path %>
           - <%= link_to "Log out", logout_path, method: "delete" %>
        <% end %>
      </small>
    </p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid nso-banner">
    <%= link_to image_tag("nso-banner.gif",
        alt: "Nevada Science Olympiad Banner Image",
        class: "img-responsive center-block"),
        root_path %>
</div>

app/views/layouts/_navlink.html.erb
<li class="<%= raw "active" if current_page?(link[:path]) %>"><%= link_to "#{link[:name]}", link[:path] %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> - Nevada Science Olympiad</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container panel" id="content-container">
    <div class="row">
        <nav class="col-md-2 nso-nav-left panel">
            <h3 class="panel-heading">Site pages</h3>
            <ul class="nav nav-pills nav-stacked">
                <%= render :partial => 'layouts/navlink', :collection => @navlinks, :as => :link %>
            </ul>
        </nav>


        <section class="col-md-10 panel panel">
            <h2 class="jumbotron panel-heading"><%= yield(:title) %></h2>
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <div class="panel-body well">
                <%= yield %>
            </div>
        </section>
    </div>
    </div>

    <%= render 'layouts/footer' %>
</body>

</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: 'POST', // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>